version: '3.8'

services:
  # Redis for memory management
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Ollama for local LLM
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    # Pull the Mistral model on startup
    command: >
      sh -c "ollama serve & sleep 10 && ollama pull mistral && tail -f /dev/null"

  # API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - design_data:/app/designs
      - order_data:/app/orders
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LLM_PROVIDER=mistral
      - LOG_LEVEL=INFO
      - DEFAULT_LANGUAGE=vi
    depends_on:
      - redis
      - ollama
    restart: unless-stopped

volumes:
  redis_data:
  ollama_models:
  design_data:
  order_data: