name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11']
        test-type: [unit, integration, regression]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    - name: Run ${{ matrix.test-type }} tests
      run: |
        if [ "${{ matrix.test-type }}" == "unit" ]; then
          pytest tshirt_fulfillment/tests/unit/ --cov=tshirt_fulfillment
        elif [ "${{ matrix.test-type }}" == "integration" ]; then
          pytest tshirt_fulfillment/tests/integration/ --cov=tshirt_fulfillment
        elif [ "${{ matrix.test-type }}" == "regression" ]; then
          pytest tshirt_fulfillment/tests/regression/ --cov=tshirt_fulfillment
        fi
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.python-version }}-${{ matrix.test-type }}
        path: .coverage