name: Python Lint and Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 build setuptools wheel pytest pytest-cov
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 tshirt_fulfillment/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 tshirt_fulfillment/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run static type checking
      run: |
        pip install mypy
        mypy tshirt_fulfillment/
    - name: Build package
      run: |
        python -m build
    - name: Run tests before packaging
      run: |
        pytest tshirt_fulfillment/tests/unit/ --cov=tshirt_fulfillment
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/